version: '3.8'
services:
  web:
    build:
      context: ./app
    command: gunicorn pizza.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  static_volume:
  postgres_data:
  media_volume:
  vhost:
  acme: