version: '3.8'

services:
  web:
    build: .
    restart: always
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env
    environment:
      - SQL_HOST=db
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
    depends_on:
      - db
  db:
    container_name: pg_container
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  dbadmin:
    container_name: dbadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
  
  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - web
    ports:
      - 80:8000
    volumes:
      - static-data:/vol/static

volumes:
  postgres_data:
  static-data: