version: '3.8'

services:
  web:
    build: ./pizza
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./pizza/:/usr/src/pizza/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pizza
      - POSTGRES_PASSWORD=pizza
      - POSTGRES_DB=pizza

  dbadmin:
    container_name: dbadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'

volumes:
  postgres_data:
