# Generated by Django 4.1.1 on 2022-09-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Topping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topping",
                    models.CharField(
                        help_text="Enter a topping",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pizza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Create a pizza", max_length=64, unique=True
                    ),
                ),
                (
                    "toppings",
                    models.ManyToManyField(
                        related_name="pizzas", to="pizza_api.topping"
                    ),
                ),
            ],
        ),
    ]
