# Generated by Django 4.1.1 on 2022-09-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pizza",
            name="toppings",
            field=models.ManyToManyField(max_length=60, to="pizza_api.toppings"),
        ),
    ]
